'use strict';

// ── Thời gian ──
const MSK_OFFSET_MS = 3 * 60 * 60 * 1000; // UTC+3 Moscow
const REPORT_HOUR   = 20;
const REPORT_MINUTE = 30;

// ── IndexedDB ──
const DB_NAME = 'xuong-sx';
const DB_VER  = 1;
const STORE   = 'reports';

// ── Danh sách tổ sản xuất ──
const TEAMS = [
  'Tổ 1',
  'Tổ 2',
  'Tổ 3',
  'Kiểm hàng',
  'Đóng gói',
  'Tổ cắt',
];

// ── Công đoạn theo từng tổ ──
const PROCESSES_BY_TEAM = {
  'Tổ 1': [
    'Cắt nhám cứng, mềm 38',
    'Cắt nhám cứng, mềm 25',
    'Cắt nhám cứng, mềm 20',
    'Cắt nhám mềm 50',
    'Cắt khóa số 5 (khóa thân trước)',
    'Cắt khóa số 5 (khóa tay)',
    'Cắt khóa số 5 (khóa sườn)',
    'Cắt khóa số 3 (khóa túi lót)',
    'Cắt dây dệt 6mm',
    'Cắt dây dệt 10mm',
    'Cắt dây dệt 25mm',
    'Cắt dây dệt 75mm',
    'Cắt chun 2,5mm',
    'Cắt chun 4cm',
    'Cắt dây dệt 2,3mm (đai)',
    'Cắt đỉa cạp x6',
    'Cắt chun đen',
    'Cắt dây chun tròn to (gấu quần x6)',
    'Cắt dây chun tròn nhỏ (gấu lót x2)',
    'Cắt dây chun tròn nhỏ (gấu áo x1)',
    'Cắt dây chun tròn nhỏ (mũ ngắn x2)',
    'Cắt dây chun tròn nhỏ (mũ dài x1)',
    'SD Túi To',
    'SD Túi trên',
    'SD Túi dưới',
    'SD Cạp',
    'SD Chun đai',
    'VS 5C Chắp đũng sau',
    'VS 5C Chắp cầu mông',
    'VS 5C can đáp gấu lót',
    'VS 5C Chắp chân sau',
    'VS 5C Chắp can đũng sau',
    'VS 5C chắp lót gối',
    'Lộn quần',
    'VS 3C đầu đáp túi to',
    'Chắp giàng 1k',
    'Chắp đũng sau 1k',
    'VS 3c giàng',
    'VS 3c đáp moi, nc',
    'Ghim khóa vào đón moi',
    'VS 3C Đáp túi To',
    'VS 3c túi to',
    'VS 3c Túi trên',
    'VS 3c túi dưới',
    'VS 5c đáp túi trong x2, nc',
    'VS 3c Quây đáy túi lưới x2, nc',
    'VS 3c đũng trước x2, nc',
    'VS 5C Can phối trên gối x2, nc',
    'VS 5C Chắp can gối vào ống dưới',
    'VS 5C chắp lộn 3 lá phối, lót gối',
    'VS 5C chắp dọc',
    'VS 3c đầu lót gối x2, nc',
    'VS 3c cạp trước ngoài',
    'VS 3c cạp sau ngoài',
    'Diễu đũng sau, nc',
    'Diễu cầu mông, nc',
    'Diễu can thân sau',
    'Diễu phối trên gối',
    'Diễu phối dưới gối',
    'Diễu can gối',
    'Diễu dọc',
    'Quây cá x4, nc',
    'Lộn cá x4',
    'Mí cá x4, nc',
    'May nhám cá x4',
    'Gim cá vào ống quần x4, nc',
    'Chiết ly túi dưới x2, nc',
    'Chiết ly, mí ly gối x2, nc',
    'Chắp can gối 1k x2, nc',
    'May ốp phối gối x2, nc',
    'Xỏ dây gấu+chốt x2',
    'May lộn miệng túi tròn x2, nc',
    'Dán ốp trang trí túi tròn x2, nc',
    'Bấm nhả miệng túi tròn',
    'Ghim miệng túi tròn',
    'Diễu miệng túi tròn 2k x2, nc',
    'Đóng túi trên vào thân trước x2, nc',
    'May nắp túi trên vào thân trước',
    'Diễu nắp túi trên',
    'Mí đáp túi tròn x2, nc',
    'Đóng túi to x2, nc',
    'May nắp túi to',
    'Diễu nắp túi to',
    'Chặn chằng túi trong vào dọc quần x2, nc',
    'Đóng túi dưới',
    'May nắp túi dưới',
    'Diễu nắp túi dưới x2, nc',
    'Diễu cá x2, nc',
    'Chiết ly túi to x2, nc',
    'Chắp đáp cạnh túi to',
    'Mí đáp miệng túi to x2, nc',
    'Mí đáp miệng túi trên x2, nc',
    'Mí đáp miệng túi dưới x2, nc',
    'Chiết ly túi trên x2, nc',
    'Kê mí đáp túi to x2, nc',
    'Gập chặn miệng túi to x2, nc',
    'Diễu miệng túi to x2, nc',
    'May nhám miệng túi to, đặt dây cúc x2',
    'Kê mí đáp túi trên',
    'Gập chặn miệng túi trên x2',
    'Diễu miệng túi trên x2',
    'May nhám miệng túi trên',
    'Kê mí đáp túi dưới x2',
    'Gập chặn miệng túi dưới x2',
    'Diễu miệng túi dưới x2',
    'May nhám miệng túi dưới x2',
    'Quây đón moi',
    'Lộn đón moi',
    'Mí đón moi',
    'May đáp moi, mí đáp moi',
    'Chắp đũng trước, tra khóa, diễu moi, diễu đũng trước',
    'Diễu can đũng sau',
    'May gấu lót 2k x2',
    'Lộn túi lưới x2',
    'Diễu túi lưới',
    'Diễu giàng',
    'Can đỉa',
    'Ke đỉa',
    'Chặn đỉa, nc',
    'May nhám đầu cạp',
    'Kéo khóa',
    'May trang trí cạp sau',
    'May nhám cạp sau',
    'Can đáp gấu quần x2',
    'Sang dấu tra gấu',
    'Ghép đáp gấu lót vào chính',
    'Tra mí gấu chính vào quần',
    'Mí đáp gấu x2',
    'Diễu đầu gối lót',
    'Diễu dọc gối x2',
    'Can nối cạp trong',
    'Can nối cạp ngoài',
    'Chặt chun vào cạp',
    'Đặt dây treo cạp',
    'Gọt lộn hai đầu cạp',
    'Đặt xốp diễu sống cạp',
    'May nhám vào chun cạp x2',
    'Chặn dây chun cạp x2',
    'Đặt đỉa',
    'Đặt mác',
    'Tra cạp',
    'Mí cạp',
    'Diễu gấu 2k, x2',
  ],
  'Tổ 2': [
    'Bẻ mí 1cm, đáp cổ',
    'Can đáp cổ',
    'Mí cạnh dưới can đáp cổ',
    'Xếp ly đầu cổ x2',
    'Can đáp đầu cổ x2',
    'Ghim cổ',
    'Mí đáp đầu cổ',
    'Chắp sống cổ 3 lá',
    'Xỏ chốt dây mũ ngắn x2',
    'Xỏ chốt dây mũ dài x1',
    'Xỏ dây dệt, chốt bọc đầu dây mũ ngắn x2, nc',
    'Xỏ dây dệt, chốt bọc đầu dây mũ dài x1, nc',
    'Luồn dây đỉnh mũ, chặn 2 đầu x1, nc',
    'Xỏ chốt 2 đầu đáp cửa mũ x2, nc',
    'Quây cá mũ',
    'Gọt cá mũ',
    'Lộn cá mũ',
    'Mí cá mũ',
    'Gắn+chặn dây dệt+diễu cá mũ',
    'Chắp đáp cửa mũ',
    'Mí đáp cửa mũ',
    'Chắp mũ trên',
    'Chắp mũ dưới',
    'Mí mũ trên',
    'Mí mũ dưới',
    'Can nối dây ốp mũ',
    'Diễu ốp mũ 2k',
    'Diễu cửa mũ',
    'Mí đáp túi bút',
    'Cắt đáp túi bút',
    'May túi bút vào thân trước trái',
    'VS 3c, lót túi tay 3 lá',
    'VS 3c đáp đầu cổ',
    'VS 3c túi lót trong',
    'VS 3c ốp cá vai',
    'VS 3c ốp tay x2',
    'VS 3c đáp túi bút',
    'Xỏ khóa túi thân trước x2',
    'Xỏ khóa túi tay x2',
    'Xỏ khóa túi sườn x4',
    'Xỏ khóa túi lót x1',
    'SD lót lưới x2',
    'SD tay x2',
    'Tra khóa túi lót',
    'Bổ góc túi lót',
    'Chắp cạnh trên miệng túi lót',
    'Mí miệng túi lót',
    'Quây túi lót',
    'Lộn túi lót x1',
    'Đóng túi vào lót lưới+dán mác x2',
    'Gập chặn ốp tay x2',
    'Chiết ly ốp tay',
    'Mí ly ốp tay',
    'Lộn ốp tay x2',
    'Diễu miệng ốp tay x2',
    'Đóng ốp tay x2',
    'Chắp cạnh trên lót túi lưới x2',
    'Diễu cạnh trên lót túi lưới',
    'Trần đè túi lưới x2',
    'Ghim lót túi lưới',
    'Đặt ống luồn dây gấu',
    'Chắp vai con sau x2',
    'Chắp vai con trước x2',
    'Chắp tam giác x2',
    'Chắp tay ngang x2',
    'Chắp sườn trước x2',
    'Chắp sườn sau x2',
    'Viền vai con sau x2',
    'Viền vai con trước x2',
    'Viền sườn sau x2',
    'Viền sườn trước x2',
    'Viền mũ trên',
    'Viền mũ dưới',
    'Diễu 2k sườn trước x2',
    'Diễu 2k vai con sau x2',
    'Diễu 2k vai con trước x2',
    'Diễu tay trên x2',
    'Chắp tay dọc x2 VS 5c',
    'Diễu tay dọc x2',
    'Diễu tay ngang x2',
    'Ghim lót túi tay',
    'Can đáp gấu',
    'May đáp gấu',
    'Mí đáp gấu',
    'Chắp 3 lá túi tay',
    'Chiết ly túi tay',
    'Ghim mũ vào cổ',
    'Tra cổ mũ',
    'Chắp mũ trên vào mũ dưới',
    'Đặt dây treo cổ sau',
    'Tra khóa nẹp',
    'Gập chặn đáp gấu',
    'Xén khóa nẹp',
    'Viền khóa nẹp',
    'Mí nẹp',
    'Mí cổ',
    'Quây lộn phủ 1k',
    'Lộn mí phủ',
    'VS 3c nẹp phủ',
    'Tra diễu nẹp phủ',
    'May nhám đầu cổ',
    'May 1cm 2 đầu ốp cá vai x2',
    'Chắp ốp cá vai x2',
    'Chặn đầu ốp cá vai x2',
    'May miếng xỏ dây gấu x2',
    'Xỏ dây gấu+xỏ chốt',
    'Chặn đầu dây gấu, lộn gấu',
    'Diễu gấu',
    'Diễu cửa tay x2',
    'May+diễu cá tay x2',
    'Xỏ dây gấu+chặn chốt sườn gấu x2',
    'Lộn áo',
    'Xỏ ốp cá vai x2',
    'Gọt cá vai',
    'Lộn cá vai',
    'Mí cá vai',
    'Ghim cá vào tam giác x2',
    'Quây cá tay',
    'Lộn cá tay',
    'Mí cá tay',
    'Nhặt chỉ nhám',
  ],
  'Tổ 3': [
    'LT sống cạp',
    'LT nắp túi nhỏ x4',
    'LT nhám chân quần x4',
    'LT nhám lót gối x2',
    'LT nhám gối x2',
    'LT khóa túi trước x2',
    'LT Nhám túi tay x2',
    'LT Khóa túi tay x2',
    'LT nhám vai x2',
    'LT nhám cá vai x2',
    'LT Nhám cửa tay x2',
    'LT nhám cá tay x2',
    'LT nhám cá mũ x1',
    'LT nhám má mũ x2',
    'LT nhám đỉnh mũ x1',
    'LT nhám+quây lộn nẹp',
    'LT nhám thân trước',
    'LT nhám ốp tay x2',
    'LT khóa túi sườn x2',
    'LT cổ 3 nhám',
    'LT cổ 1 nhám',
    'Viền túi trước x2',
    'Viền túi tay x2',
    'Viền túi sườn x2',
    'Gọt, viền đầu khóa túi trước',
    'Gọt viền đầu khóa, túi tay x2',
    'Gọt, viền đầu khóa túi sườn x2',
    'Gập chặn, cắt đầu dây ke túi tay x3, nc',
    'Gập chặn, cắt đầu dây ke túi trước x2, nc',
    'Gập chặn cắt đầu ke túi sườn x2, nc',
    'Chiết ly sau túi tay x2',
    'Mí sung quanh túi trước x2',
    'Mí sung quanh túi tay x2',
    'Gọt, lộn nắp túi nhỏ x4',
    'Mí nắp túi nhỏ x4',
    'Là nẹp',
    'Là cạp trong',
    'Là cạp ngoài',
    'Là dây chống bai miệng túi tròn x2',
    'Là cửa tay x2',
    'May lộn nắp túi to trong x2, nc',
    'Mí nắp túi to trong x2, nc',
    'Ghim nắp túi to x2, nc',
    'May nhám nắp túi to trong x2, nc',
    'May lộn nắp túi to ngoài x2, nc',
    'Mí nắp túi to ngoài x2, nc',
    'Bọ cá mũ (2)',
    'Bọ đáp cửa mũ x2',
    'Bọ dây lót túi tay x2 (10)',
    'Bọ cơi túi tay x2 (4)',
    'Bọ cơi túi trước x2 (4)',
    'Bọ ly sau túi tay x2 (4)',
    'Bọ ốp tay x2 (4)',
    'Bọ đầu khóa túi tay (6)',
    'Bọ đầu khóa túi trước (6)',
    'Bọ thành phẩm áo',
    'Bọ nắp túi to x2',
    'Thùa nắp túi to x2',
    'Bọ đầu khóa nẹp (6)',
    'Bọ cự ly cạp ngoài x2',
    'Bọ tròn túi to x2',
    'Thùa gấu lót x2',
    'Bọ cạp hoàn thiện',
    'Xỏ cúc túi quần',
    'Bọ dây cúc túi to x2 (0,6mm)',
    'Bọ thành phẩm thân trên',
    'Bọ thành phẩm thân dưới',
    'May dây cố định đai, nc',
    'May nhám đai x4, nc',
    'Đục, dập oze cửa mũ x4',
    'Đục, dập oze đỉnh mũ x2',
    'Đục, dập oze gấu áo x4',
    'Đục, dập oze gấu quần x2',
    'Bổ cơi túi trước',
    'Chặn ngạnh trê túi trước',
    'Ghim cơi túi trước',
    'Mí cơi túi trước',
    'Mí cơi túi tay',
    'Mí túi trước',
    'Mí túi tay 1k',
    'Bổ cơi túi tay',
    'Chặn ngạnh trê túi tay',
    'Bổ túi sườn',
    'Chặn ngạnh trê túi sườn',
    'Mí túi sườn',
    'Cắt mác số',
    'Đếm mác số',
    'Đếm mác trang trí',
    'Viền khóa thân trước',
    'Viền khóa sườn',
    'Viền túi tay',
    'Viền đầu khóa túi trước',
    'Viền đầu khóa sườn',
    'Viền đầu khóa túi tay',
    'Chặn, cắt đầu dây túi trước',
    'Chặn, cắt đầu dây túi sườn',
    'Chặn, cắt đầu dây túi tay',
    'Gọt nắp túi nhỏ trên',
    'Lộn nắp túi nhỏ trên',
    'Mí nắp túi nhỏ trên',
    'Gọt nắp túi nhỏ dưới',
    'Lộn nắp túi nhỏ dưới',
    'Mí nắp túi nhỏ dưới',
    'VS 3c nắp túi nhỏ trên',
    'VS 3c nắp túi nhỏ dưới',
    'VS 5c chắp tay dọc',
    'Xỏ ốp cá tay',
  ],
  'Kiểm hàng':             [],
  'Đóng gói':              [],
  'Tổ cắt':                [],
};

// Fallback khi chưa chọn tổ
const PROCESSES_DEFAULT = [
  'Cắt', 'May thân', 'May tay', 'May cổ',
  'Thùa khuy', 'Đính cúc', 'Là',
  'Kiểm tra chất lượng', 'Đóng gói',
  'Vận hành máy dệt', 'Vận hành máy in',
];

function getProcessList(team) {
  return PROCESSES_BY_TEAM[team] || PROCESSES_DEFAULT;
}

// Trả về danh sách có đánh số thứ tự để hiển thị trong dropdown
function getNumberedProcessList(team) {
  return getProcessList(team).map((p, i) => (i + 1) + '. ' + p);
}
